<?php

use Illuminate\Database\Seeder;
/**
 * Generated by PoGoDB 4 Laravel
 */
class LaravelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //inserts
    }
}
